/* dbsvr_service_impl.cpp

 Generated by phxrpc_pb2service from dbsvr.proto

*/

#include "dbsvr_service_impl.h"

#include "phxrpc/file.h"

#include "dbsvr_server_config.h"
#include "dbsvr.pb.h"


using namespace std;


DbsvrServiceImpl::DbsvrServiceImpl(ServiceArgs_t &app_args) : args_(app_args) {
}

DbsvrServiceImpl::~DbsvrServiceImpl() {
}

int DbsvrServiceImpl::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    resp->set_value(req.value());
    return 0;
}

int DbsvrServiceImpl::Set(const dbsvr::SetReq &req, dbsvr::SetResp *resp) {
	SimpleRedis Reids("127.0.0.1", 6379);
	int iRet = Reids.HSet( "htable", req.key(), req.value() );
	if( 0 != iRet  )
	{
		printf("DbsvrServiceImpl::Set fail %d\n", iRet);
	}
	resp->set_code( iRet );
    return iRet;
}

int DbsvrServiceImpl::Get(const dbsvr::GetReq &req, dbsvr::GetResp *resp) {
	SimpleRedis Reids("127.0.0.1", 6379);
	std::string value;
	int iRet = Reids.HGet( "htable", req.key(), value);
	if( 0 != iRet  )
	{
		printf("DbsvrServiceImpl::Get fail %d\n", iRet);
	}
	resp->set_code(iRet);
	resp->set_value( value );
    return iRet;
}

