/* dbsvr_service_impl.cpp

 Generated by phxrpc_pb2service from dbsvr.proto

*/

#include "dbsvr_service_impl.h"

#include "phxrpc/file.h"

#include "dbsvr_server_config.h"
#include "dbsvr.pb.h"


using namespace std;


DbsvrServiceImpl::DbsvrServiceImpl(ServiceArgs_t &app_args) : args_(app_args) {
}

DbsvrServiceImpl::~DbsvrServiceImpl() {
}

int DbsvrServiceImpl::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    resp->set_value(req.value());
    return 0;
}

int DbsvrServiceImpl::Set(const dbsvr::SetReq &req, dbsvr::SetResp *resp) {
    return -1;
}

int DbsvrServiceImpl::Get(const dbsvr::GetReq &req, dbsvr::GetResp *resp) {
    return -1;
}

