/* dbsvr_server_config.cpp

 Generated by phxrpc_pb2server from dbsvr.proto

*/

#include "dbsvr_server_config.h"

#include "dbsvr.pb.h"


DbsvrServerConfig::DbsvrServerConfig() {
}

DbsvrServerConfig::~DbsvrServerConfig() {
}

bool DbsvrServerConfig::Read(const char *config_file) {
    bool ret{ep_server_config_.Read(config_file)};

    if (0 == strlen(ep_server_config_.GetPackageName())) {
        ep_server_config_.SetPackageName(
                dbsvr::SetReq::default_instance().GetDescriptor()->file()->package().c_str());
    }

    return ret;
}

phxrpc::HshaServerConfig &DbsvrServerConfig::GetHshaServerConfig() {
    return ep_server_config_;
}

