/* dbsvr_tool_impl.h

 Generated by phxrpc_pb2tool from dbsvr.proto

*/

#pragma once

#include "phxrpc_dbsvr_tool.h"


namespace phxrpc {


class OptMap;


}


class DbsvrToolImpl : public DbsvrTool {
  public:
    DbsvrToolImpl();
    virtual ~DbsvrToolImpl() override;

    virtual int PHXEcho(phxrpc::OptMap &opt_map) override;
    virtual int Set(phxrpc::OptMap &opt_map) override;
    virtual int Get(phxrpc::OptMap &opt_map) override;
};

