/* dbsvr_service_impl.h

 Generated by phxrpc_pb2service from dbsvr.proto

*/

#pragma once

#include "dbsvr.pb.h"
#include "phxrpc_dbsvr_service.h"


class DbsvrServerConfig;

typedef struct tagServiceArgs {
    DbsvrServerConfig *config;
    // you can add other arguments here and initiate in main().
} ServiceArgs_t;

class DbsvrServiceImpl : public DbsvrService {
  public:
    DbsvrServiceImpl(ServiceArgs_t &app_args);
    virtual ~DbsvrServiceImpl() override;

    virtual int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) override;
    virtual int Set(const dbsvr::SetReq &req, dbsvr::SetResp *resp) override;
    virtual int Get(const dbsvr::GetReq &req, dbsvr::GetResp *resp) override;

  private:
    ServiceArgs_t &args_;
};

