/* phxrpc_dbsvr_tool.cpp

 Generated by phxrpc_pb2tool from dbsvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_dbsvr_tool.h"

#include "phxrpc/file.h"

#include "dbsvr_client.h"


using namespace phxrpc;


DbsvrTool::DbsvrTool() {
}

DbsvrTool::~DbsvrTool() {
}

int DbsvrTool::PHXEcho(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PHXEcho unimplement ***\n");

    return -1;
}

int DbsvrTool::Set(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** Set unimplement ***\n");

    return -1;
}

int DbsvrTool::Get(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** Get unimplement ***\n");

    return -1;
}

