/* phxrpc_dbsvr_stub.cpp

 Generated by phxrpc_pb2client from dbsvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_dbsvr_stub.h"

#include "phxrpc/http.h"
#include "phxrpc/network.h"
#include "phxrpc/rpc.h"


DbsvrStub::DbsvrStub(phxrpc::BaseTcpStream &socket, phxrpc::ClientMonitor &client_monitor,
        phxrpc::BaseMessageHandlerFactory &msg_handler_factory)
        : socket_(socket), client_monitor_(client_monitor),
          msg_handler_factory_(msg_handler_factory) {
}

DbsvrStub::~DbsvrStub() {
}

void DbsvrStub::set_keep_alive(const bool keep_alive) {
    keep_alive_ = keep_alive;
}

int DbsvrStub::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/dbsvr/PHXEcho", -1);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int DbsvrStub::Set(const dbsvr::SetReq &req, dbsvr::SetResp *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/dbsvr/Set", 1);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int DbsvrStub::Get(const dbsvr::GetReq &req, dbsvr::GetResp *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/dbsvr/Get", 2);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

