/* phxrpc_dbsvr_dispatcher.h

 Generated by phxrpc_pb2service from dbsvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_dbsvr_dispatcher.h"

#include <errno.h>

#include "phxrpc/http.h"
#include "phxrpc/file.h"

#include "dbsvr.pb.h"
#include "phxrpc_dbsvr_service.h"


DbsvrDispatcher::DbsvrDispatcher(DbsvrService &service, phxrpc::DispatcherArgs_t *dispatcher_args)
        : service_(service), dispatcher_args_(dispatcher_args) {
}

DbsvrDispatcher::~DbsvrDispatcher() {
}

const phxrpc::BaseDispatcher<DbsvrDispatcher>::URIFuncMap &DbsvrDispatcher::GetURIFuncMap() {
    static phxrpc::BaseDispatcher<DbsvrDispatcher>::URIFuncMap uri_func_map = {
        {"/dbsvr/PHXEcho", &DbsvrDispatcher::PHXEcho},
        {"/dbsvr/Set", &DbsvrDispatcher::Set},
        {"/dbsvr/Get", &DbsvrDispatcher::Get}};
    return uri_func_map;
}

int DbsvrDispatcher::PHXEcho(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(-1, "PHXEcho", 1);

    int ret{-1};

    google::protobuf::StringValue req_pb;
    google::protobuf::StringValue resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.PHXEcho(req_pb, &resp_pb);
        }
    }

    // pack response
    {
        if (0 != resp->FromPb(resp_pb)) {
            phxrpc::log(LOG_ERR, "FromPb err %d", ret);

            return -ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: PHXEcho = %d", ret);

    return ret;
}

int DbsvrDispatcher::Set(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(1, "Set", 1);

    int ret{-1};

    dbsvr::SetReq req_pb;
    dbsvr::SetResp resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.Set(req_pb, &resp_pb);
        }
    }

    // pack response
    {
        if (0 != resp->FromPb(resp_pb)) {
            phxrpc::log(LOG_ERR, "FromPb err %d", ret);

            return -ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: Set = %d", ret);

    return ret;
}

int DbsvrDispatcher::Get(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(2, "Get", 1);

    int ret{-1};

    dbsvr::GetReq req_pb;
    dbsvr::GetResp resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.Get(req_pb, &resp_pb);
        }
    }

    // pack response
    {
        if (0 != resp->FromPb(resp_pb)) {
            phxrpc::log(LOG_ERR, "FromPb err %d", ret);

            return -ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: Get = %d", ret);

    return ret;
}

