/* phxrpc_dbsvr_dispatcher.h

 Generated by phxrpc_pb2service from dbsvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "phxrpc/rpc.h"


class DbsvrService;

class DbsvrDispatcher {
  public:
    static const phxrpc::BaseDispatcher<DbsvrDispatcher>::URIFuncMap &GetURIFuncMap();

    DbsvrDispatcher(DbsvrService &service, phxrpc::DispatcherArgs_t *dispatcher_args);

    virtual ~DbsvrDispatcher();

    int PHXEcho(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);
    int Set(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);
    int Get(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);

  private:
    DbsvrService &service_;
    phxrpc::DispatcherArgs_t *dispatcher_args_;
};

