/* phxrpc_dbsvr_service.cpp

 Generated by phxrpc_pb2service from dbsvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_dbsvr_service.h"

#include "dbsvr.pb.h"
#include "phxrpc/file.h"


DbsvrService::DbsvrService() {
}

DbsvrService::~DbsvrService() {
}

int DbsvrService::PHXEcho(const google::protobuf::StringValue &/* req */, google::protobuf::StringValue */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: PHXEcho unimplemented");
    return -1;
}

int DbsvrService::Set(const dbsvr::SetReq &/* req */, dbsvr::SetResp */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: Set unimplemented");
    return -1;
}

int DbsvrService::Get(const dbsvr::GetReq &/* req */, dbsvr::GetResp */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: Get unimplemented");
    return -1;
}

