/* phxrpc_dbsvr_service.h

 Generated by phxrpc_pb2service from dbsvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "dbsvr.pb.h"


class DbsvrService {
  public:
    DbsvrService();
    virtual ~DbsvrService();

    virtual int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    virtual int Set(const dbsvr::SetReq &req, dbsvr::SetResp *resp);
    virtual int Get(const dbsvr::GetReq &req, dbsvr::GetResp *resp);
};

