/* phxrpc_dbsvr_tool.h

 Generated by phxrpc_pb2tool from dbsvr.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once


namespace phxrpc {


class OptMap;


}


class DbsvrTool {
  public:
    DbsvrTool();
    virtual ~DbsvrTool();

    virtual int PHXEcho(phxrpc::OptMap &bigmap);
    virtual int Set(phxrpc::OptMap &bigmap);
    virtual int Get(phxrpc::OptMap &bigmap);

    typedef int (DbsvrTool::*ToolFunc_t)(phxrpc::OptMap &);

    typedef struct tagName2Func {
        const char *name;
        DbsvrTool::ToolFunc_t func;
        const char *opt_string;
        const char *usage;
    } Name2Func_t;

    static Name2Func_t *GetName2Func() {
        static Name2Func_t name2func[]{
            {"PHXEcho", &DbsvrTool::PHXEcho, "c:f:vs:",
                    "-s <string>"},
            {"Set", &DbsvrTool::Set, "c:f:vk:a:",
                    "-k <key> -a <value>"},
            {"Get", &DbsvrTool::Get, "c:f:vk:",
                    "-k <key>"},
            {nullptr, nullptr}
        };

        return name2func;
    };
};

