/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 0;
extern const char* const kSvnInfo[0] = {};
extern const char kBuildType[] = "debug";
extern const char kBuildTime[] = "Mon Feb 25 23:06:11 2019";
extern const char kBuilderName[] = "godman";
extern const char kHostName[] = "localhost.localdomain";
extern const char kCompiler[] = "GCC 4.8.2";
}}
